# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EvaluateTeam.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(70, 70, 381, 20))
        self.line.setStyleSheet("c\n"
"gridline-color: rgb(19, 19, 19);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.calcscore = QtWidgets.QPushButton(Dialog)
        self.calcscore.setGeometry(QtCore.QRect(190, 330, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.calcscore.setFont(font)
        self.calcscore.setStyleSheet("color: rgb(129, 129, 129);\n"
"border-color: rgb(104, 104, 104);")
        self.calcscore.setObjectName("calcscore")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(80, 10, 361, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(82, 42, 361, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.teamname = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.teamname.setFont(font)
        self.teamname.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"\n"
"color: rgb(50, 50, 50);")
        self.teamname.setObjectName("teamname")
        self.teamname.addItem("")
        self.teamname.addItem("")
        self.teamname.addItem("")
        self.horizontalLayout.addWidget(self.teamname)
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.matchname = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.matchname.setFont(font)
        self.matchname.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);")
        self.matchname.setObjectName("matchname")
        self.matchname.addItem("")
        self.matchname.addItem("")
        self.matchname.addItem("")
        self.horizontalLayout.addWidget(self.matchname)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(80, 100, 151, 221))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.players = QtWidgets.QLineEdit(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.players.setFont(font)
        self.players.setFrame(False)
        self.players.setObjectName("players")
        self.horizontalLayout_2.addWidget(self.players)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.splayers = QtWidgets.QScrollArea(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.splayers.setFont(font)
        self.splayers.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(87, 87, 87);")
        self.splayers.setWidgetResizable(True)
        self.splayers.setObjectName("splayers")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 147, 191))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(130, 0, 16, 191))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.splayers.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.splayers)
        self.widget3 = QtWidgets.QWidget(Dialog)
        self.widget3.setGeometry(QtCore.QRect(290, 100, 144, 221))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.points = QtWidgets.QLineEdit(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.points.setFont(font)
        self.points.setFrame(False)
        self.points.setObjectName("points")
        self.horizontalLayout_4.addWidget(self.points)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.spoints = QtWidgets.QScrollArea(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.spoints.setFont(font)
        self.spoints.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(87, 87, 87);")
        self.spoints.setWidgetResizable(True)
        self.spoints.setObjectName("spoints")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 140, 191))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(120, 0, 16, 191))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.spoints.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.spoints)
        self.actionEVALUATE_TEAM_4 = QtWidgets.QAction(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionEVALUATE_TEAM_4.setFont(font)
        self.actionEVALUATE_TEAM_4.setObjectName("actionEVALUATE_TEAM_4")
        self.actionEVALUATE_TEAM_5 = QtWidgets.QAction(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.actionEVALUATE_TEAM_5.setFont(font)
        self.actionEVALUATE_TEAM_5.setObjectName("actionEVALUATE_TEAM_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Evaluate Your Team"))
        self.calcscore.setText(_translate("Dialog", "Calculate Score"))
        self.label.setText(_translate("Dialog", "Evaluate the Performance of your Fantasy Team"))
        self.teamname.setItemText(0, _translate("Dialog", "Internshala"))
        self.teamname.setItemText(1, _translate("Dialog", "virtual team1"))
        self.teamname.setItemText(2, _translate("Dialog", "virtual team2"))
        self.matchname.setItemText(0, _translate("Dialog", "Match1"))
        self.matchname.setItemText(1, _translate("Dialog", "Match2"))
        self.matchname.setItemText(2, _translate("Dialog", "Match3"))
        self.label_2.setText(_translate("Dialog", "Players"))
        self.label_4.setText(_translate("Dialog", "Points"))
        self.actionEVALUATE_TEAM_4.setText(_translate("Dialog", "EVALUATE Team"))
        self.actionEVALUATE_TEAM_5.setText(_translate("Dialog", "EVALUATE Team"))


##if __name__ == "__main__":
##    import sys
##    app = QtWidgets.QApplication(sys.argv)
##    Dialog = QtWidgets.QDialog()
##    ui = Ui_Dialog()
##    ui.setupUi(Dialog)
##    Dialog.show()
##    sys.exit(app.exec_())
